In [2]:
import pandas as pd

In [4]:
cards_merged = pd.read_csv('data/cards_merged.csv')

,name,id,maxEvolutionLevel,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
0,Knight,26000000,3.0,3.0,common,202.0,1766.0,troop,ground,ground,single,False,8.88,51.79
1,Archers,26000001,1.0,3.0,common,214.0,304.0,troop,ground,both,single,True,1.44,46.10
2,Goblins,26000002,2.0,2.0,common,360.0,202.0,troop,ground,ground,single,True,3.60,54.32
3,Giant,26000003,2.0,5.0,rare,254.0,4090.0,troop,ground,buildings,single,False,2.32,59.10
4,P.E.K.K.A,26000004,1.0,7.0,epic,816.0,3760.0,troop,ground,ground,single,False,3.28,50.61

In [9]:
print(cards_merged.isnull().sum())
cards_merged.describe()

name                  0
id                    0
maxEvolutionLevel    73
elixirCost            1
rarity                0
damage11             29
hitpoints            20
type                  1
mobility              1
targets               1
attack_type           2
groupCard             1
usage                 2
Win Rate              2
dtype: int64

,id,maxEvolutionLevel,elixirCost,damage11,hitpoints,usage,Win Rate
count,1.210000e+02,48.000000,120.000000,92.000000,101.000000,119.000000,119.000000
mean,2.648764e+07,1.291667,3.975000,428.619565,1264.435644,5.337143,53.292605
std,7.970185e+05,0.581939,1.541921,444.015786,1024.305320,6.127417,3.805675
min,2.600000e+07,1.000000,1.000000,0.000000,81.000000,0.160000,43.880000
25%,2.600003e+07,1.000000,3.000000,192.750000,560.000000,1.760000,50.975000
50%,2.600006e+07,1.000000,4.000000,265.500000,1000.000000,3.280000,53.230000
75%,2.700000e+07,1.000000,5.000000,518.250000,1697.000000,7.280000,56.205000
max,2.800003e+07,3.000000,9.000000,2580.000000,5120.000000,42.880000,61.780000