# Importing Libraries

In [3]:
import pandas as pd
import numpy as np
import plotly.express as px
import scipy.cluster.hierarchy as sch
import matplotlib.pyplot as plt
import seaborn as sns
import dataframe_image as dfi

# Data Import

## Scraping data

In [ ]:
# https://developer.clashroyale.com
import requests

# Ask Aiden for Token or IP help
TOKEN = ''
URL = "https://api.clashroyale.com/v1/cards" # change url ending for different data

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/json"
}

def get_cards_to_csv():
    try:
        # Request data from API
        response = requests.get(URL, headers=headers)
        
        # Check if the request was successful
        if response.status_code == 200:
            data = response.json()
            
            # Convert the 'items' list into a DataFrame
            df = pd.json_normalize(data['items'])
            
            print("Successfully retrieved card data.")
            return df # Preview the first few rows
            
        else:
            print(f"Failed to fetch data. Status Code: {response.status_code}")
            print(f"Error Message: {response.text}")
            
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    ClashRoyaleAPI_cards_df = get_cards_to_csv()

ClashRoyaleAPI_cards_df.columns

## Card Data

In [15]:
cards_df = pd.read_csv('./data/cards_merged.csv')
cards_df.head()

,name,id,maxEvolutionLevel,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
0,Knight,26000000,3.0,3.0,common,202.0,1766.0,troop,ground,ground,single,False,8.88,51.79
1,Archers,26000001,1.0,3.0,common,214.0,304.0,troop,ground,both,single,True,1.44,46.10
2,Goblins,26000002,2.0,2.0,common,360.0,202.0,troop,ground,ground,single,True,3.60,54.32
3,Giant,26000003,2.0,5.0,rare,254.0,4090.0,troop,ground,buildings,single,False,2.32,59.10
4,P.E.K.K.A,26000004,1.0,7.0,epic,816.0,3760.0,troop,ground,ground,single,False,3.28,50.61

## Deck Data

In [28]:
decks_df = pd.read_csv('./data/decks.csv')
decks_df.head()

,card1,card2,card3,card4,card5,card6,card7,card8,wild,usage,Win Rate
0,Lumberjack,Balloon,Executioner,Skeleton Army,Skeletons,Freeze,The Log,Cannon,"['evo', 'hero', 'evo']",0.7,67.7
1,Battle Ram,Wizard,Royal Ghost,Giant Skeleton,Mother Witch,Vines,Zappies,Barbarian Barrel,"['evo', 'hero', 'evo']",0.5,67.6
2,Mortar,Goblins,Minion Horde,Miner,Cannon Cart,Skeleton Dragons,Rascals,Arrows,"['evo', 'hero', 'evo']",0.8,63.6
3,Skeleton Barrel,Goblins,Mortar,Cannon Cart,Fireball,Minions,Rascals,Barbarian Barrel,"['evo', 'hero', 'evo']",4.7,63.3
4,Skeleton Barrel,Bowler,Mortar,Fireball,Dart Goblin,Rascals,Skeletons,Barbarian Barrel,"['evo', 'hero', 'evo']",0.7,63.2

## Counting null values

In [16]:
cards_clean_df = cards_df.copy()
cards_df.isnull().sum()

name                  0
id                    0
maxEvolutionLevel    73
elixirCost            1
rarity                0
damage11             29
hitpoints            20
type                  1
mobility              1
targets               1
attack_type           2
groupCard             1
usage                 2
Win Rate              2
dtype: int64

### `maxEvolutionLevel`

In [17]:
cards_clean_df.rename(columns={'maxEvolutionLevel': 'wild'}, inplace=True)
cards_clean_df['wild'] = cards_df['maxEvolutionLevel'].replace({np.nan: 'normal', 1: 'evo', 2: 'hero', 3: 'both'})
cards_clean_df.head()

,name,id,wild,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
0,Knight,26000000,both,3.0,common,202.0,1766.0,troop,ground,ground,single,False,8.88,51.79
1,Archers,26000001,evo,3.0,common,214.0,304.0,troop,ground,both,single,True,1.44,46.10
2,Goblins,26000002,hero,2.0,common,360.0,202.0,troop,ground,ground,single,True,3.60,54.32
3,Giant,26000003,hero,5.0,rare,254.0,4090.0,troop,ground,buildings,single,False,2.32,59.10
4,P.E.K.K.A,26000004,evo,7.0,epic,816.0,3760.0,troop,ground,ground,single,False,3.28,50.61

In [10]:
cards_clean_df['wild'].isnull().sum()

np.int64(0)

### `damage11` and `hitpoints`

In [18]:
cards_df.loc[(cards_df['damage11'].isnull()) | (cards_df['hitpoints'].isnull())].head()

,name,id,maxEvolutionLevel,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
31,Fire Spirit,26000031,NaN,1.0,common,NaN,230.0,troop,ground,ground,single,False,1.76,51.20
64,Firecracker,26000064,1.0,3.0,common,NaN,304.0,troop,ground,both,splash,False,8.08,50.15
65,Mighty Miner,26000065,NaN,4.0,champion,NaN,2250.0,troop,ground,ground,single,False,4.24,57.00
67,Battle Healer,26000068,NaN,4.0,rare,NaN,1717.0,troop,flying,ground,single,False,1.44,56.07
68,Skeleton King,26000069,NaN,4.0,champion,NaN,2298.0,troop,ground,ground,splash,False,3.68,57.40

These missing values can be replaced manually using domain knowledge. Missing `hitpoints` values primarily belong to spell-type cards, which lack health in the original game.

In [19]:
cards_clean_df.rename(columns = {'hitpoints': 'hitpoints11'}, inplace = True)
cards_clean_df.loc[31, 'damage11'] = 207
cards_clean_df.loc[64, 'damage11'] = 320
cards_clean_df.loc[65, 'damage11'] = 40
cards_clean_df.loc[67, 'damage11'] = 148
cards_clean_df.loc[68, 'damage11'] = 204
cards_clean_df.loc[69, 'damage11'] = 225
cards_clean_df.loc[70, 'damage11'] = 161
cards_clean_df.loc[71, 'damage11'] = 140
cards_clean_df.loc[72, 'damage11'] = 161
cards_clean_df.loc[73, 'damage11'] = 133
cards_clean_df.loc[74, 'damage11'] = 99
cards_clean_df.loc[75, 'damage11'] = 163
cards_clean_df.loc[76, 'damage11'] = 217
cards_clean_df.loc[77, 'damage11'] = 104
cards_clean_df.loc[78, 'damage11'] = 186
cards_clean_df.loc[79, 'damage11'] = 212
cards_clean_df.loc[80, 'damage11'] = 256
cards_clean_df.loc[81, 'damage11'] = 128
cards_clean_df.loc[82, 'damage11'] = 120
cards_clean_df.loc[83, 'damage11'] = 102
cards_clean_df.loc[84, 'damage11'] = 245
cards_clean_df.loc[97, 'damage11'] = 120
cards_clean_df.loc[100, 'damage11'] = 179
cards_clean_df.loc[111, 'damage11'] = 0
cards_clean_df.loc[114, 'damage11'] = 110
cards_clean_df.loc[116, 'damage11'] = 437
cards_clean_df.loc[117, 'damage11'] = 1020
cards_clean_df.loc[118, 'damage11'] = 210
cards_clean_df.loc[119, 'damage11'] = 307
cards_clean_df.loc[120, 'damage11'] = 306
cards_clean_df.loc[114, 'type'] = 'troop'
cards_clean_df.loc[119, 'hitpoints11'] = 1177
cards_clean_df['damage11'].isnull().sum()

np.int64(0)

### Unique missing values

Card 104 is the unique Mirror card. Its values cannot be easily replaced, so we omitted it during analysis. Cards 119 and 120 are the Spirit Empress and Vines cards, which were added too recently to be included in the Kaggle datasets we used. Their values were added manually.

In [24]:
cards_clean_df.loc[119, ['type', 'mobility', 'targets', 'attack_type', 'groupCard', 'usage', 'Win Rate']] = ['troop', 'flying', 'both', 'single', 'False', 4.80, 54.23]
cards_clean_df.loc[120, ['usage', 'Win Rate']] = [4.80, 53.21]
cards_clean_df.drop(104).isnull().sum()

name            0
id              0
wild            0
elixirCost      0
rarity          0
damage11        0
hitpoints11    18
type            0
mobility        0
targets         0
attack_type     0
groupCard       0
usage           0
Win Rate        0
dtype: int64

## Exporting data

In [25]:
cards_clean_df.drop(104).to_csv('./data/cards_cleaned.csv', index = False)
cards_clean_df.to_csv('./data/cards_cleaned_with_mirror.csv', index = False)

# Regression modeling